# Generated by Django 5.2.1 on 2025-05-30 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
    ]
