# Generated by Django 5.2.1 on 2025-06-01 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0002_initial'),
    ]

    operations = [
    ]
