# Generated by Django 5.2.3 on 2025-06-17 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.AlterModelOptions(
            name='aturangejala',
            options={},
        ),
        migrations.AlterModelOptions(
            name='detailaturan',
            options={},
        ),
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'verbose_name_plural': 'Diagnosis'},
        ),
        migrations.AlterModelOptions(
            name='gejala',
            options={'verbose_name_plural': 'Gejala'},
        ),
        migrations.AlterModelOptions(
            name='laporandiagnosis',
            options={'verbose_name_plural': 'Laporan Diagnosis'},
        ),
        migrations.AlterModelOptions(
            name='laporangejala',
            options={'verbose_name_plural': 'Laporan Gejala'},
        ),
        migrations.AlterModelOptions(
            name='pengguna',
            options={},
        ),
    ]
